##########################
# GDD 2025
##########################

#FROM python
#FROM localhost/mysql-test-getvalues:latest
FROM docker.io/dditrani/debian-python-1.0:latest

#USER 0

#WORKDIR /home/desa/python/getvalues
#INSTALACION para python

RUN pip3 install fastapi  && \  
    pip3 install "uvicorn[standard]" && \
    pip install mysql-connector-python &&\
    pip install curl_cffi



#EJECUTAR la app python con uvicorn

#CMD uvicorn home.desa.python.getvalues.main:app --host 0.0.0.0 --port 80  --reload
#build
# podman build -f dockerfile-fastapi -t dockerfile-fastapi

#----------------------------------------------
#DESPUES DE BUILDEAR LA IMAGEN PARA CORRER EL CONTAINER 

#para ejecutar la imagen montandole un volumen contra el host:
#para ejecutar en la VDI
# podman run -it -p 8081:80 -v /mnt/c/Users/l0646482/n/mi_desa2/python/getvalues:/home/desa/python/getvalues --name dockerfile-fastapi dockerfile-fastapi

#para ejecutar en la maquina W10
#podman run -it -p 8081:80 -v /mnt/c/Users/papa/n/desa/python/getvalues:/home/desa/python/getvalues --name dockerfile-fastapi dockerfile-fastapi
